=== SimplyRecruit/taas/public/locales/schemas/forgot-password.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "description": "",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "minLength": 1
        },
        "title": {
            "type": "string",
            "minLength": 1
        },
        "login": {
            "type": "string",
            "minLength": 1
        },
        "error-500": {
            "type": "string",
            "minLength": 1
        },
        "error-404": {
            "type": "string",
            "minLength": 1
        },
        "error-403": {
            "type": "string",
            "minLength": 1
        },
        "success": {
            "type": "string",
            "minLength": 1
        }
    },
    "required": [
        "$schema",
        "title",
        "login",
        "error-500",
        "error-404",
        "error-403",
        "success"
    ],
    "additionalProperties": false
}

=== SimplyRecruit/taas/public/locales/tr/forgot-password.json
{
    "$schema": "../schemas/forgot-password.json",
    "title": "Şifremi Unuttum",
    "login": "Giriş yap",
    "error-500": "Bir şeyler yanlış gitti. Lütfen tekrar deneyin.",
    "error-404": "Böyle bir hesap bulunmamaktadır.",
    "error-403": "Bu hesap henüz doğrulanmadı. Hesabınızı doğrulamak için lütfen e-postanızı kontrol edin.",
    "success": "Parolanızı sıfırlamak için bir bağlantı için e-postanızı kontrol edin. Birkaç dakika içinde görünmezse spam klasörünüzü kontrol edin."
}

=== SimplyRecruit/taas/public/locales/en/forgot-password.json
{
    "$schema": "../schemas/forgot-password.json",
    "title": "Forgot Password",
    "login": "Log in",
    "error-500": "Something went wrong. Please try again.",
    "error-404": "No account with this email.",
    "error-403": "This account is not verified. Please check your email to verify your account.",
    "success": "Check your email for a link to reset your password. If it doesnâ€™t appear within a few minutes, check your spam folder."
}
